package com.mycompany.tictacthesis;


import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rayst
 */
public class Tik extends javax.swing.JFrame {

    /**
     * Creates new form Tik
     */
    public Tik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    static int player = 0;
    static String[]field = {" "," "," "," "," "," "," "," "," "};
    static String[] x = {"  ","  ","  ","  ","  ","  ","  ","  ","  "};
    static boolean playing = true;
    static String letter = "X";
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box1 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();
        box4 = new javax.swing.JButton();
        box5 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        box9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        box1.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box1.setText(" ");
        box1.setToolTipText("");
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box2.setText(" ");
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box3.setText(" ");
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box4.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box4.setText(" ");
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box5.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box5.setText(" ");
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box6.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box6.setText(" ");
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box7.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box7.setText(" ");
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box8.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box8.setText(" ");
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        box9.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        box9.setText(" ");
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Your Turn!");

        reset.setFont(new java.awt.Font("InputSerifNarrow Medium", 0, 36)); // NOI18N
        reset.setText("RESET");
        reset.setToolTipText("");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(box1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel1)))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(box8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
     x[0] =    checkOccupied(box1);
        checkWin(box1);
    }//GEN-LAST:event_box1ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
     x[1] =    checkOccupied(box2);
        checkWin(box2);
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
      x[2] =   checkOccupied(box3);
        checkWin(box3);
    }//GEN-LAST:event_box3ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
      x[3] =   checkOccupied(box4);
        checkWin(box4);
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
      x[4] =   checkOccupied(box5);
        checkWin(box5);
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
      x[5] =   checkOccupied(box6);
        checkWin(box6);
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
      x[6] =   checkOccupied(box7);
        checkWin(box7);
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
       x[7] =  checkOccupied(box8);
        checkWin(box8);
    }//GEN-LAST:event_box8ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
        x[8] = checkOccupied(box9);
        checkWin(box9);
    }//GEN-LAST:event_box9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetGame();
        JOptionPane.showMessageDialog(this,"Resetted!");
    }//GEN-LAST:event_resetActionPerformed

    
    
    private String checkOccupied(javax.swing.JButton b){
        
        String text = b.getText();
        System.out.println(b);
        if(b.getText() != " "){
            JOptionPane.showMessageDialog(b,"That place is already occupied!");
        }else{
            text = checkPlayer(player);
            b.setText(text);
        }
        return text;
    }
    
    private void checkWin(javax.swing.JButton b){
        display(x);
        if(!contains(x,"  ")){
            checkTrueAll(b);
        }
        checkTrue(b);
    }

    public static boolean contains(final String[] arr, final String key) {
        return Arrays.stream(arr).anyMatch(i -> i == key);
    }
    
    private void checkTrue(javax.swing.JButton b){
        System.out.println(x);
        if(x[0] == "X" && x[1] == "X" && x[2] == "X" || x[3] == "X" && x[4] == "X" && x[5] == "X" || x[6] == "X" && x[7] == "X" && x[8] == "X" ||
                x[0] == "X" && x[3] == "X" && x[6] == "X" || x[1] == "X" && x[4] == "X" && x[7] == "X" || x[2] == "X" && x[5] == "X" && x[8] == "X" ||
                    x[0] == "X" && x[4] == "X" && x[8] == "X" || x[2] == "X" && x[4] == "X" && x[6] == "X" || x[6] == "X" && x[7] == "X" && x[8] == "X" ){
            resetGame();
            JOptionPane.showMessageDialog(b,"Player Won!");
        }else if(x[0] == "O" && x[1] == "O" && x[2] == "O" || x[3] == "O" && x[4] == "O" && x[5] == "O" || x[6] == "O" && x[7] == "O" && x[8] == "O" ||
                x[0] == "O" && x[3] == "O" && x[6] == "O" || x[1] == "O" && x[4] == "O" && x[7] == "O" || x[2] == "O" && x[5] == "O" && x[8] == "O" ||
                    x[0] == "O" && x[4] == "O" && x[8] == "O" || x[2] == "O" && x[4] == "O" && x[6] == "O" || x[6] == "O" && x[7] == "O" && x[8] == "O" ){
            resetGame();
            JOptionPane.showMessageDialog(b,"Robot Won!");
        }else{
        }
    }
    private void checkTrueAll(javax.swing.JButton b){
        if(x[0] == "X" && x[1] == "X" && x[2] == "X" || x[3] == "X" && x[4] == "X" && x[5] == "X" || x[6] == "X" && x[7] == "X" && x[8] == "X" ||
                x[0] == "X" && x[3] == "X" && x[6] == "X" || x[1] == "X" && x[4] == "X" && x[7] == "X" || x[2] == "X" && x[5] == "X" && x[8] == "X" ||
                    x[0] == "X" && x[4] == "X" && x[8] == "X" || x[2] == "X" && x[4] == "X" && x[6] == "X" ){
            resetGame();
            JOptionPane.showMessageDialog(b,"Player Won!");
        }else if(x[0] == "O" && x[1] == "O" && x[2] == "O" || x[3] == "O" && x[4] == "O" && x[5] == "O" || x[6] == "O" && x[7] == "O" && x[8] == "O" ||
                x[0] == "O" && x[3] == "O" && x[6] == "O" || x[1] == "O" && x[4] == "O" && x[7] == "O" || x[2] == "O" && x[5] == "O" && x[8] == "O" ||
                    x[0] == "O" && x[4] == "O" && x[8] == "O" || x[2] == "O" && x[4] == "O" && x[6] == "O"  ){
            resetGame();
            JOptionPane.showMessageDialog(b,"Robot Won!");
        }else {
            resetGame();
            JOptionPane.showMessageDialog(b,"Draw..!");
        }
    }
    
    private void display(String [] a){
        for(int i = 0; i < a.length ;i++){
            System.out.println(a[i]);
        }
    }
    
    

    
    private String checkPlayer(int p){
        if(p == 0){
            
            letter = "X";
            player++;
            jLabel1.setText("Robot's Turn!");
            return "X";
        }else{
            letter = "O";
            player--;
            jLabel1.setText("Your Turn!");
            return "O";
        }
    }
    
    private void resetGame(){
        box1.setText(" ");
        box2.setText(" ");
        box3.setText(" ");
        box4.setText(" ");
        box5.setText(" ");
        box6.setText(" ");
        box7.setText(" ");
        box8.setText(" ");
        box9.setText(" ");
        
        for(int i = 0; i < x.length;i++){
            x[i] = "  ";
        }
        letter = "X";
        playing = true;
        player = 0;
        jLabel1.setText("Your Turn!");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JButton box9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
